version: 2.1

jobs:
  build:
    docker:
      - image: node:14
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm i express
      - run: npm i ws
      - run: npm i node-binance-api
      - run: npm i request
      - run: npm i technicalindicators
      - run: npm i readline
      - run: npm i fs
      - run: npm i inspector
      - run: npm i crypto
      - name: Run Buy_Sell_macd.js script
      - command: node Buy_Sell_macd.js

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
